services:
  postgres:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sixvault
      - POSTGRES_DB=sixvault
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sixvault-core:
    build:
      context: .
      args:
        DATABASE_URL: postgresql://postgres:sixvault@postgres:5432/sixvault
        JWT_ACCESS_SECRET: test
        JWT_REFRESH_SECRET: test
    ports:
      - "3000:3000" 
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:sixvault@postgres:5432/sixvault
    depends_on:
      - postgres

volumes:
  postgres_data:
