services:
  mysql:
    image: mysql:9.3.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sixvault
      - MYSQL_DATABASE=sixvault
      - MYSQL_USER=sixvault
      - MYSQL_PASSWORD=sixvault
    volumes:
      - mysql_data:/var/lib/mysql

  # sixvault-core:
  #   build:
  #     context: .
  #   ports:
  #     - "${PORT}:${PORT}"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mysql

volumes:
  mysql_data: