services:
  postgres:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sixvault
      - POSTGRES_DB=sixvault
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # sixvault-core:
  #   build:
  #     context: .
  #   ports:
  #     - "${PORT}:${PORT}"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mysql

volumes:
  postgres_data: